### PR TITLE
fix(core): removed default selection styling (NDS-90)

### PR DESCRIPTION
**Pull request by Apatil15**
Fix [NDS-90 ](https://wwnorton.atlassian.net/browse/NDS-90)

### CODE REVIEW

**Comment by sh0ji** [comment]
The docs job is failing. Fix that and this is good to go, @Apatil15.

**Comment by Apatil15** [comment]
Fixed in color.mdx changed default values for selection-background-color and selection-text-color

**Review by sh0ji — APPROVED** [review]
LGTM. If we ever want to support this in the future, we'll have to re-add the `::selection` declaration, but I'm okay with leaving it out for now.

**Comment by sh0ji** [comment]
Oh, and just for future reference: this was a `refactor` commit type since it doesn't fix anything that's broken (`fix`)&mdash;it's just changing how things work internally. An argument could be made for `feat` since it's removing an existing feature, but that feature wasn't documented so I'm okay with calling it a refactor.

**Pull request merged**
