### PR TITLE
update(typesets): [NDS-265] heading updates for website only

### PR DESCRIPTION
**Pull request by wguevara-norton**

### CODE REVIEW

**Review by sh0ji — CHANGES_REQUESTED** [review]
When making updates to the website, please don't change anything in the libraries (core, react). If we need to make changes to the design system itself, let's open a ticket to describe that work and do it in a separate PR. Website updates should just update the website.

All that said, it looks like the original regression happened in https://github.com/wwnorton/design-system/pull/227 (specifically, dec0e7311d3b4dc5211203c55c1d1ba72e65a84c), which is possibly the cause of #226 as well. Rather than fixing that here, let's revert all changes to https://github.com/wwnorton/design-system/blob/main/packages/core/src/type/index.scss and open a separate PR to address that issue as a bug fix.

**Comment by JRebella** [comment]
Any idea why those attributes needed the `!important` in first place?

Also I agree with Evan, that original PR seems to have caused the spacing issues in the modal
image

**Comment by wguevara-norton** [comment]
Actually, the modal issue is different and it's older than this code fragment

**Comment by sh0ji** [comment]
> Any idea why those attributes needed the `!important` in first place?

That was added in dec0e73, which we missed.

> Actually, the modal issue is different and it's older than this code fragment

I think you're right that the issue is older but the top margin _is_ causing an issue currently, as @JRebella pointed out. Let's move that to a separate PR, though.

The goal for the typeset margins is to only have one vertical margin set to improve [vertical rhythm](https://betterwebtype.com/articles/2018/10/15/rhythm-in-web-typography/). In other words, we should use top or bottom margin for typographic spacing, but never both. Very early on in our typography planning, we decided on bottom margins, partly because it's what Bootstrap uses and partly because it's [slightly more popular](https://css-tricks.com/margin-bottom-margin-top/). I'm not opposed to switching to top margins, but that would be a breaking change.

**Pull request closed without merging**
