### PR TITLE
Badge and Tag documentation

### PR DESCRIPTION
**Pull request by erinoh**
Added new documentation file for badge and tag component

https://pr-172.d2xq18ppjtz6lz.amplifyapp.com/

### CODE REVIEW

**Comment by sh0ji** [comment]
Thanks, Erin! I'll make some small formatting changes and add these documents to our sidebar so that we can see them in our test environment.

**Comment by sh0ji** [comment]
Great stuff, @erinoh!

The little fixes that I made are purely syntax fixes, and only one of them was preventing the docs from building. Both of the changes are related to how [Docusaurus](https://docusaurus.io/) markdown features work. Docusaurus is the framework we use for docs.

* [Frontmatter](https://docusaurus.io/docs/docs-markdown-features#markdown-frontmatter) fields cannot be multiline, which was preventing the docs from building. You can see [the change I made in this diff](https://github.com/wwnorton/design-system/pull/172/commits/0c74358b82124f12e4c1b011eccfd259d23cfd03#diff-8c1cbd98dd74e47bac5f3d2fc3790c52c37047eb28899d1aa18dd9e8f78028d0L3-R3), which shows that I changed lines 3 & 4 of Tag to be just one line.
* You had a space after the `:::` in your [admonitions](https://docusaurus.io/docs/markdown-features/admonitions), which was preventing them from rendering properly.

FYI @Apatil15, @wguevara-norton.

**Comment by sh0ji** [comment]
I made a couple more changes:

* Use design system Callouts instead of the Docusaurus admonitions (bb085b2).
   * The syntax for our callouts is a bit more involved, so I think if you want to just use the `:::tip` syntax going forward, that's fine. We'll replace it during the PR like I just did.
* Add initial anatomy descriptions (0f1e316).
   * All other components describe the role or purpose of each part of the anatomy. I think this is very helpful but also very difficult. I'm fine taking on most anatomy description for future components.
   * The one thing I didn't describe is the `icon` because I'm not too sure what purpose it serves in the anatomy. Any ideas, @erinoh?

And before this is merged, I'd like to tighten up the component descriptions a little bit. Here's what I'm thinking:

For badge:
> A badge brings attention to information about a related component.

This mirrors [Callout](https://wwnorton.github.io/design-system/docs/components/callout/), which is also used for supplemental information but in a different context. I originally had "metadata" instead of "information" but that felt too jargony to me.

For tag:
> A tag allows the user to interact with or dismiss a status or classification.

Most (all?) of our components that are interactive start with "X allows the user to...", which I think especially helps differentiate Tag from Badge. Badge is presentational, whereas Tag allows the user to _do_ something. And "interact with or dismiss" captures the fact that it can be dissmisible or more generically interactive.

**Comment by sh0ji** [comment]
@erinoh: I updated the Badge description and removed icon from the anatomy. We can add icon back if we can come up with a good description of its role or justification for why it's part of badge and not just a separate component that you can compose together with badge.

@Apatil15 & @wguevara-norton: I also updated the docs to include the "React API" section, which required the following steps in case you need to do something similar in the future:

* merged the Badge implementation (#154) into this branch (aace8b5)
* added Badge to the public components export (3fe5151). We both missed this in #154, @Apatil15. whoops!
* added a simple React API section (fb3ffba). This should always cover a) a list of components that it exposes (many just expose one, but some expose multiple components), b) what interface it extends (`React.HTMLAttributes<HTMLSpanElement>`), c) how to import it, d) a very simple live code example, and e) the props table, which is generated from your JSDoc descriptions in the code.
* added both Badge and Tag to `website/sidebar.js` (bc0a341). Note that this should be alphabetical with the exception of the index, which should come first, and React Providers, which should come last.
* added a card for Badge to the `/docs/components/index.mdx` file (ed80b56). This should follow the same order as the sidebar, minus the self-reference (index).

**Comment by erinoh** [comment]
> @erinoh: I updated the Badge description and removed icon from the anatomy. We can add icon back if we can come up with a good description of its role or justification for why it's part of badge and not just a separate component that you can compose together with badge.

@sh0ji Let's discuss this in the meeting today if we have time. We do include icon in the button anatomy.

**Comment by sh0ji** [comment]
Very odd that there's a coverage change here since this change didn't touch any of the corresponding code. I'm going to merge this anyway. Thanks, @erinoh!

**Pull request merged**
