### PR TITLE
refactor(nds-213): removed thumbnails including tks images

### PR DESCRIPTION
**Pull request by Apatil15**
Removed thumbnails including TKs images. Please review it

### CODE REVIEW

**Comment by sh0ji** [comment]
Looks like there's now just empty space where the images were: https://pr-239.d2xq18ppjtz6lz.amplifyapp.com/docs/components

image

That whole card "cap" should be removed, shouldn't it, @erinoh?

**Comment by erinoh** [comment]
@sh0ji @Apatil15 Yeah, the whole image part of the card should be removed so they'll only include the title/description portion.

**Comment by Apatil15** [comment]
@erinoh Are we planning to update thumbnails in future? In case yes I will not delete all the implementation :) 
@sh0ji

**Comment by Apatil15** [comment]
@sh0ji I have updated thumbnails, Please verify.
https://pr-239.d2xq18ppjtz6lz.amplifyapp.com/docs/components/

**Comment by sh0ji** [comment]
LGTM! Thanks, @Apatil15.

**Pull request merged**
