### PR TITLE
chore: added glob pattern for windows

### PR DESCRIPTION
**Pull request by lucas-contreras**

### CODE REVIEW

**Comment by sh0ji** [comment]
Interesting, do you know why this fixes things for Windows?

Just speculating, but if Storybook's using something like [globby](https://github.com/sindresorhus/globby) to parse the config's `stories`, then using Node's `path.resolve` might be creating a string that Storybook's parser doesn't know what to do with. I've seen issues like that with OS-specific pathing before.

**Review by cafrias — APPROVED** [review]

**Comment by sh0ji** [comment]
@cafrias, are you able to merge this or should I?

**Comment by cafrias** [comment]
@sh0ji I'm not authorized to merge

**Comment by sh0ji** [comment]
This was fixed by #318, so I'm closing it.

**Pull request closed without merging**
